version: '3.9'

services:
  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-app
    depends_on:
      - users-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-db:5432/users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8081:8081
  users-db:
    image: postgres:latest
    restart: always
    container_name: my-users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - 5432:5432